--- 
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: postgresql
    tier: backend
spec:
  ports:
  - name: pgsql
    port: 5432
  selector:
    app: postgresql
    tier: backend
